# Example package with demo entities and an automation
# Adjust entity names or add more devices if needed.
light:
  - platform: demo
    name: Demo Lamp  # change name to customize entity_id

sensor:
  - platform: demo
    name: Demo Temperature

automation:
  - alias: "Demo: turn on lamp at sunset"
    trigger:
      - platform: sun
        event: sunset
    action:
      - service: light.turn_on
        target:
          entity_id: light.demo_lamp
